### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by khanzadimahdi** [tzsk/sms#14]
please add new release for new features and update composer. tnx.

**Comment by khanzadimahdi** [comment]
@tzsk please release the package in github, i want to use it in my project. tnx.

**Comment by tzsk** [comment]
@khanzadimahdi Well you can use `composer require tzsk/sms:dev-master`.

I still don't like the `withDriver()` function I'll make it `via()` then push a new release. Because of the DDD principal. It reads better. Also, will do a SMS Builder for the notificaion channel.

I'm also considering to change the syntax to `Sms::via($gateway)->send($body)->to($recipients)->dispatch()`. And also make it loggable and event drivent. So there is that.

If you want I can make an `RC` release for now.

**Comment by khanzadimahdi** [comment]
> @khanzadimahdi Well you can use `composer require tzsk/sms:dev-master`.
> 
> I still don't like the `withDriver()` function I'll make it `via()` then push a new release. Because of the DDD principal. It reads better. Also, will do a SMS Builder for the notificaion channel.
> 
> I'm also considering to change the syntax to `Sms::via($gateway)->send($body)->to($recipients)->dispatch()`. And also make it loggable and event drivent. So there is that.
> 
> If you want I can make an `RC` release for now.
please have a seen on Channel ,we have `withDriver` method in that file , it should be change into `via`

**Comment by tzsk** [comment]
Done & `1.3.0-rc` is out now. Thanks.

**Comment by khanzadimahdi** [comment]
tnx my bro.
