### ISSUE TITLE
Now it returns the raw response received from the Gateway Unchanged

### ISSUE THREAD

**Issue by khanzadimahdi** [tzsk/sms#16]
hi , do u think returning the raw response recieved from gateway is a good idea? i think its not SOLID!
what do u think if i create a response wrapper for drivers ? agree with it or not?

**Comment by tzsk** [comment]
Hi, @khanzadimahdi I certainly don't think it is a good idea to return RAW Response. But for the time being it is the solution that works until we come up with a Wrapper that supports all kinds of Response.

I know it is ugly, but I have been getting requests for releasing the new gateways so I did. And to not mess up old installations I made it a Major release.

I have some ideas in mind will have to think and try out how it plays with the various types of responses.

Also, it is difficult to try out, because I don't have the response structure of many of the Gateways.

**Comment by khanzadimahdi** [comment]
ok bro. i will work on it too.

**Comment by tzsk** [comment]
@khanzadimahdi I'll ask for a favor. If you can get me the response bodies for different gateways in separate text files. I can quickly get a Wrapper class up and running.

**Comment by khanzadimahdi** [comment]
let me research and think on it. we need a standard response here.

**Comment by khanzadimahdi** [comment]
hey , i've founded a way.
 the response must be in the below format: 

```php
[
	status: error,
	'numbers' => [
		'number1' => [
			'status' : 'success',
			'message' => null,
		],
		'number2' => [
			'status' : 'error',
			'message' => 'api max execution time error!',
		],
		'number2' => [
			'status' : 'success',
			'message' => null,
		],
	]
]
```
as you see , the we have a main `status` that describes if the whole send process. if an error occures for sending sms to `even one of the numbers` we change both `status` of the main array and the number array. so the programmer can checks the main status, and if it is equal to `error` can find the numbers that have `error status` and retrieve the `api` given message. 
what's your idea?

**Comment by khanzadimahdi** [comment]
i think you can create a wrapper class that generates this output array! and the send method must return that wrapper object or throws an exception.
