### ISSUE TITLE
what to use, Hash or Api in textlocal?

### ISSUE THREAD

**Issue by aquib-jawed04** [tzsk/sms#175]
I'm using hashkey but the message is not being sent.

**Comment by tzsk** [comment]
@aquib-jawed04 Hash should work and did work for me.

Few things you need to verify for Textlocal
- Check your Textlocal Balance.
- Get the approval of your SMS templates from Textlocal otherwise, you won't get the SMS.
- Make sure the text you send is exactly like the template approved (to the dot).

If all of the above doesn't work then check the response you are getting from Textlocal if there is any issue while sending then it should let you know and also check the logs at the Textlocal Dashboard it should show you if there is any issue.
