### ISSUE TITLE
I think some drivers need to be refactored 

### ISSUE THREAD

**Issue by mohaphez** [tzsk/sms#925]
Why is foreach used in most drivers to send SMS to multiple numbers?
While 90% of the providers support simultaneous reception of several receivers.

In this case, to send SMS to 100 recipients, 100 connections must be created.
While it is easily sent with a connection.

On the other hand, an array of 100 items should be returned to the user as a response.
And the user parses it again with foreach.
While one answer is enough for all 100 item.

what is your opinion ?
If you agree, I will refactor the drivers that support this feature.

**Comment by tzsk** [comment]
Hi @mohaphez ,

This has been one of my biggest gripes about making the decision that I made. I certainly like the idea. But if we were to refactor it then it should follow a certain consistency.

- The response should follow a uniform return type.
- We need to somehow unify both single / batch calls into that type.

The purpose of this Driver Based SMS Integration is so that consumers can swap the config out anytime to a different provider and all things should work magically. (Unless they defined the driver inline for multi-driver setup).

Now as of today, they would have to make changes in their result handling to achieve that.

Let me know if you find any good common ground between all the drivers so that we can achieve this ideal state.

**Comment by mohaphez** [comment]
Hi dear @tzsk 

Your point is well taken!

This is one of the problems preventing everything from work magically. There is no driver parser.

I know that developers only need BatchId after sending SMS. While we get the answer directly from the provider and return it to the user, then the user must once again read the provider's documentation or put the answer in var_dump to find out how to get the BatchId.

This makes it change the way of parsing its response again by changing the gateway.

In my opinion, we should add a function to the drivers called getBachId. That each driver converts its response into a single format.

Upon receiving the SMS response, we separate the batchIds and put them into an array with a specific format and return it to the user. With this, the user will be able to change his gateway dynamically without worrying about anything,Because it will be sure to receive BatchId in the same format.

But since some providers return a BatchId for each receiver. And some others return only one string for all receptors.
It is better for our single answer to be an array, such as:

```
[
   'batchId' =>[ 'b1','b2'],
   'providerResponse' => []  // if the user need it use it
]
```
